name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Flyctl Login
        env:
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
        run: flyctl auth token $FLY_TOKEN

      - name: Deploy
        run: flyctl deploy
